title: Malik's Portfolio of Cybersecurity Projects
description: Turning ideas into action with hands-on projects that solve real-world challenges.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
